/**
 * Generates src/data/emoji-data.ts from unicode-emoji-json + emojilib.
 *
 * Runs at build time so the app never parses the raw datasets at runtime.
 * Each emoji is a compact tuple: [emoji, name, version, keywords, toneTemplate?]
 * where toneTemplate contains "{t}" after every Emoji_Modifier_Base code point,
 * so skin tones apply correctly even to multi-person ZWJ sequences.
 */
import { createRequire } from 'node:module';
import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const groups = require('unicode-emoji-json/data-by-group.json');
const keywordsByEmoji = require('emojilib');

const OUT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '../src/data/emoji-data.ts'
);

const MODIFIER_BASE = /\p{Emoji_Modifier_Base}/u;
const VS16 = '️';
const ZWJ = '‍';
const HANDSHAKE = '\u{1F91D}';
const MAX_KEYWORDS = 8;

function toneTemplate(emoji) {
  const cps = Array.from(emoji);
  const hasZwj = cps.includes(ZWJ);
  let out = '';
  let inserted = false;
  for (let i = 0; i < cps.length; i++) {
    out += cps[i];
    // In RGI ZWJ sequences (e.g. "people holding hands") the linking
    // handshake never takes a modifier — only the person code points do.
    if (hasZwj && cps[i] === HANDSHAKE) continue;
    if (MODIFIER_BASE.test(cps[i])) {
      if (cps[i + 1] === VS16) i++; // tone modifier replaces the VS16
      out += '{t}';
      inserted = true;
    }
  }
  return inserted ? out : emoji + '{t}';
}

function keywordsFor(emoji, slug, name) {
  const raw = keywordsByEmoji[emoji] ?? keywordsByEmoji[emoji + VS16] ?? [];
  const seen = new Set(name.toLowerCase().split(/\s+/));
  const out = [];
  for (const kw of raw) {
    const clean = kw.replace(/_/g, ' ').toLowerCase().trim();
    if (!clean || clean === slug.replace(/_/g, ' ') || seen.has(clean)) continue;
    seen.add(clean);
    out.push(clean);
    if (out.length >= MAX_KEYWORDS) break;
  }
  return out.join(',');
}

const outGroups = [];
let count = 0;
let toneCount = 0;

for (const group of groups) {
  if (group.slug === 'component') continue;
  const emojis = group.emojis.map((e) => {
    count++;
    const tuple = [
      e.emoji,
      e.name,
      parseFloat(e.emoji_version),
      keywordsFor(e.emoji, e.slug, e.name),
    ];
    if (e.skin_tone_support) {
      tuple.push(toneTemplate(e.emoji));
      toneCount++;
    }
    return tuple;
  });
  outGroups.push({ key: group.slug, emojis });
}

const banner = `// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.
// Source: unicode-emoji-json (emoji + categories + versions) and emojilib (keywords).
// Regenerate with: npm run build-data
`;

const body = `${banner}import type { EmojiDataFile } from '../core/types';

export const EMOJI_DATA: EmojiDataFile = ${JSON.stringify({ groups: outGroups })};
`;

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, body);

console.log(
  `Wrote ${OUT}: ${outGroups.length} groups, ${count} emoji (${toneCount} with skin tones), ${(body.length / 1024).toFixed(0)} KB`
);
